#!/usr/bin/env bash

# Install scripts and dotfiles
cp -alf scripts .bash_aliases .bashrc .vimrc $HOME
cp -alf dunst vis/colors $HOME/.config

# Set up `theme` command and autocomplete
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
echo "export THEMES_DIR=$THIS_DIR" >> $HOME/.bashrc
sudo ln util/_theme_completion /etc/bash_completion.d/theme

# Install fonts
mkdir -p $HOME/.fonts
mv fonts/* $HOME/.fonts
fc-cache -f

# Make dirs
mkdir -p $HOME/.config/ps1_controller
mkdir -p $HOME/.config/polybar

# Install dunst config
#sudo mkdir /etc/dunst
#sudo ln $HOME/dunst/dunstrc /etc/dunst

# Reload
. $HOME/.bashrc
