#!/usr/bin/env python

# Background switcher using nitrogen

import sys
import os
import argparse
import subprocess
from time import sleep

parser = argparse.ArgumentParser()
parser.add_argument('directory',
        help='The directory to search for images')
parser.add_argument('-t', '--time', type=float, default=10,
        help='The amount of time to wait between new backgrounds')

args = parser.parse_args()

#parser = argpase.ArgumentParser(description='Automatically switch the background to images in a directory')
#parser.add_argument(

directory = args.directory
t = 60*args.time

while True:
    subprocess.call(["nitrogen", "--random", "--set-zoom-fill", directory])
    sleep(t)
