#!/usr/bin/env python3
"""
Theme switcher for i3wm.

This script changes i3, polybar, Xdefaults, and vis config files to update
themes. The environment variable THEMES_DIR must be exported and point to
a directory containing subdirectories called 'i3', 'polybar', 'Xdefaults' and
'vis'.

Each of these dirs should contain config files for their respective
programs. The config files for a theme should be named after the theme. For
example, for the theme 'forest', the files '$THEMES_DIR/i3/forest',
'$THEMES_DIR/polybar/forest', ... exist.

The config dirs should also each include a 'template' file which has shared
config settings accross all themes.
"""

import os
import shutil
import logging
import argparse
import subprocess
from util.urxvt_update import update_urxvt_colors
from util.ps1_controller import update_ps1

HOME = os.path.expanduser('~')
CONFIG = os.path.join(HOME, '.config')
DOTS = os.environ["THEMES_DIR"]
TEMPLATE = 'template'

I3_CONFIG = os.path.join(CONFIG, 'i3/config')
POLYBAR_CONFIG = os.path.join(CONFIG, 'polybar/config')
XDEFAULTS_CONFIG = os.path.join(HOME, '.Xdefaults')
VIS_CONFIG = os.path.join(CONFIG, 'vis/config')
PS1_CONFIG = os.path.join(CONFIG, 'ps1_controller/config')

I3_THEMES = os.path.join(DOTS, 'i3')
POLYBAR_THEMES = os.path.join(DOTS, 'polybar')
XDEFAULTS_THEMES = os.path.join(DOTS, 'Xdefaults')
VIS_THEMES = os.path.join(DOTS, 'vis')
PS1_THEMES = os.path.join(DOTS, 'ps1_controller')

I3_TEMPLATE = os.path.join(I3_THEMES, TEMPLATE)
POLYBAR_TEMPLATE = os.path.join(POLYBAR_THEMES, TEMPLATE)
XDEFAULTS_TEMPLATE = os.path.join(XDEFAULTS_THEMES, TEMPLATE)
VIS_TEMPLATE = os.path.join(VIS_THEMES, TEMPLATE)
PS1_TEMPLATE = os.path.join(PS1_THEMES, TEMPLATE)

def link(src, dst, name):
    if os.path.isfile(src):
        if os.path.exists(dst):
            os.remove(dst)
        os.link(src, dst)
    else:
        logging.warning('{} config not found at {}.'.format(name, src))

def copy(src, dst, name):
    if os.path.isfile(src):
        if os.path.exists(dst):
            os.remove(dst)
        shutil.copyfile(src, dst)
    else:
        logging.warning('{} template not found at {}.'.format(name, src))
        raise FileNotFoundError

def append(src, dst, name):
    """ Appends src to dst. """
    if os.path.isfile(src):
        with open(dst, 'a') as dst_file:
            with open(src, 'r') as src_file:
                dst_file.write('\n')
                dst_file.write(src_file.read())
    else:
        logging.warning('{} config not found at {}.'.format(name, src))
        raise FileNotFoundError

def install_templated_theme(theme, template, dst, name):
    try:
        if os.path.exists(dst):
            os.remove(dst)
        copy(template, dst, name)
        append(theme, dst, name)
    except:
        pass

if __name__ == '__main__':

    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument('theme',
            type = str,
            help = 'The name of the theme to use. The must be a corresponging \
                    file with the theme name in all style directories.')
    args = parser.parse_args()

    theme = args.theme

    i3 = os.path.join(I3_THEMES, theme)
    polybar = os.path.join(POLYBAR_THEMES, theme)
    xdefaults = os.path.join(XDEFAULTS_THEMES, theme)
    vis = os.path.join(VIS_THEMES, theme)
    ps1 = os.path.join(PS1_THEMES, theme)

    install_templated_theme(i3, I3_TEMPLATE, I3_CONFIG, 'i3')
    install_templated_theme(
                polybar, POLYBAR_TEMPLATE, POLYBAR_CONFIG, 'polybar')
    install_templated_theme(
                xdefaults, XDEFAULTS_TEMPLATE, XDEFAULTS_CONFIG, 'Xdefaults')
    install_templated_theme(vis, VIS_TEMPLATE, VIS_CONFIG, 'vis')
    install_templated_theme(ps1, PS1_TEMPLATE, PS1_CONFIG, 'ps1_controller')

    update_urxvt_colors()
    update_ps1()

    subprocess.run(['i3-msg', 'restart'])
